
#include "utilityMacros.hpp"

#define GET_REGISTRY_TAGS() (GETVARM(TAG_REGISTRY_STR, []))

#define GET_LOADOUT_VARIABLE(FACTION_ID,STRING_SUFFIX) (format ["baf_loadout_%1_%2",FACTION_ID,STRING_SUFFIX])
#define GET_LOADOUT_REGISTRY_VARIABLE(FACTION_ID) (format ["baf_registry_loadout_%1",FACTION_ID])
#define GET_LOADOUT_BAF(FACTION_ID,STRING_SUFFIX) (GETVARM(GET_LOADOUT_VARIABLE(FACTION_ID,STRING_SUFFIX),nil))
#define GET_LOADOUT_REGISTRY(FACTION_ID) (GETVARM(GET_LOADOUT_REGISTRY_VARIABLE(FACTION_ID),nil))
#define GET_LOADOUT_ARRAY(LOADOUT_BAF) (LOADOUT_BAF select 1)
#define GET_LOADOUT_TRAITS(LOADOUT_BAF) (LOADOUT_BAF select 2)
#define GET_TRAIT_MEDICAL(TRAITS) (TRAITS select 0)
#define GET_TRAIT_ENGINEERING(TRAITS) (TRAITS select 1)
// TODO: Get other traits

#define GET_CLASS_VARIABLE(FACTION_ID,STRING_SUFFIX) (format ["baf_class_%1_%2",FACTION_ID,STRING_SUFFIX])
#define GET_CLASS_REGISTRY_VARIABLE(FACTION_ID) (format ["baf_registry_class_%1",FACTION_ID])
#define GET_CLASS(FACTION_ID,STRING_SUFFIX) (GETVARM(GET_CLASS_VARIABLE(FACTION_ID,STRING_SUFFIX),nil))
#define GET_CLASS_REGISTRY(FACTION_ID) (GETVARM(GET_CLASS_REGISTRY_VARIABLE(FACTION_ID),nil))
#define GET_CLASS_LOADOUTS(CLASS_ARRAY) CLASS_ARRAY select 0
#define GET_CLASS_ARSENAL(CLASS_ARRAY) CLASS_ARRAY select 1
#define SET_CLASS_ARSENAL(CLASS_ARRAY, ARSENAL_ARRAY) CLASS_ARRAY set [1, ARSENAL_ARRAY]

#define GET_CRATE_VARIABLE(FACTION_ID,STRING_SUFFIX) (format ["baf_crate_%1_%2",FACTION_ID,STRING_SUFFIX])
#define GET_CRATE_REGISTRY_VARIABLE(FACTION_ID) (format ["baf_registry_crate_%1",FACTION_ID])
#define GET_CRATE(FACTION_ID,STRING_SUFFIX) (GETVARM(GET_CRATE_VARIABLE(FACTION_ID,STRING_SUFFIX),nil))
#define GET_CRATE_REGISTRY(FACTION_ID) (GETVARM(GET_CRATE_REGISTRY_VARIABLE(FACTION_ID),nil))
#define SET_CRATE(FACTION_ID,STRING_SUFFIX,CRATE_ARRAY) SETVARM(GET_CRATE_VARIABLE(FACTION_ID,STRING_SUFFIX),CRATE_ARRAY)

#define GET_PRIMARY(LOADOUT_ARRAY) LOADOUT_ARRAY select 0
#define GET_LAUNCHER(LOADOUT_ARRAY) LOADOUT_ARRAY select 1
#define GET_SECONDARY(LOADOUT_ARRAY) LOADOUT_ARRAY select 2
#define GET_WEAPON_NAME(WEAPON_ARRAY) WEAPON_ARRAY select 0
#define GET_WEAPON_MUZZLE_NAME(WEAPON_ARRAY) WEAPON_ARRAY select 1
#define GET_WEAPON_ATTACHMENT_NAME(WEAPON_ARRAY) WEAPON_ARRAY select 2
#define GET_WEAPON_SIGHT_NAME(WEAPON_ARRAY) WEAPON_ARRAY select 3
#define GET_WEAPON_MAG(WEAPON_ARRAY) WEAPON_ARRAY select 4
#define GET_WEAPON_UG_MAG(WEAPON_ARRAY) WEAPON_ARRAY select 5
#define GET_WEAPON_BIPOD_NAME(WEAPON_ARRAY) WEAPON_ARRAY select 6
#define GET_MAG_NAME(MAG_ARRAY) MAG_ARRAY select 0
#define GET_MAG_CAPACITY(MAG_ARRAY) MAG_ARRAY select 0

#define GET_UNIFORM(LOADOUT_ARRAY) LOAODUT_ARRAY select 3
#define GET_UNIFIROM_NAME(LOAODUT_ARRAY) GET_UNIFIROM(LOADOUT_ARRAY) select 0
#define GET_UNIFIROM_INVENTORY(LOAODUT_ARRAY) GET_UNIFIROM(LOADOUT_ARRAY) select 1
#define GET_VEST(LOADOUT_ARRAY) LOAODUT_ARRAY select 4
#define GET_VEST_NAME(LOAODUT_ARRAY) GET_VEST(LOADOUT_ARRAY) select 0
#define GET_VEST_INVENTORY(LOAODUT_ARRAY) GET_VEST(LOADOUT_ARRAY) select 1
#define GET_BACKPACK(LOADOUT_ARRAY) LOAODUT_ARRAY select 5
#define GET_BACKPACK_NAME(LOAODUT_ARRAY) GET_BACKPACK(LOADOUT_ARRAY) select 0
#define GET_BACKPACK_INVENTORY(LOAODUT_ARRAY) GET_BACKPACK(LOADOUT_ARRAY) select 1
#define GET_HELMET_NAME(LOADOUT_ARRAY) LOAODUT_ARRAY select 6
#define GET_MASK_NAME(LOADOUT_ARRAY) LOADOUT_ARRAY select 7
#define GET_BINO(LOADOUT_ARRAY) LOADOUT_ARRAY select 8
#define GET_BINO_NAME(LOADOUT_ARRAY) GET_BINO(LOADOUT_ARRAY) select 0
#define GET_UTILITIES(LOADOUT_ARRAY) LOADOUT_ARRAY select 9
#define GET_UTILITIES_MAP_NAME(LOADOUT_ARRAY) GET_UTILITIES(LOADOUT_ARRAY) select 0
#define GET_UTILITIES_TERMINAL_NAME(LOADOUT_ARRAY) GET_UTILITIES(LOADOUT_ARRAY) select 1
#define GET_UTILITIES_RADIO_NAME(LOADOUT_ARRAY) GET_UTILITIES(LOADOUT_ARRAY) select 2
#define GET_UTILITIES_COMPASS_NAME(LOADOUT_ARRAY) GET_UTILITIES(LOADOUT_ARRAY) select 3
#define GET_UTILITIES_WATCH_NAME(LOADOUT_ARRAY) GET_UTILITIES(LOADOUT_ARRAY) select 4
#define GET_UTILITIES_NVG_NAME(LOADOUT_ARRAY) GET_UTILITIES(LOADOUT_ARRAY) select 4
