
#include "utilityMacros.hpp"

#define EMPTY_LOADOUT [[[],[],[],[],[],[],"","",[],["","","","","",""]],[]]
#define DEFAULT_LOADOUT_NAME "default" // TODO: Setup default loadout
// #define FACTION_ID blufor // defined in loadout config files

// Loadout Registry: [[Loadout Variable Name,Dispaly Name],...]
// Class Registry: [[Class Variable Name,Display Name],...]
// Crate Registry: [[Crate Variable Name,Display Name],...]
#define INIT_LOADOUT_SYSTEM() \
if (isNil TAG_REGISTRY_STR) then { TAG_REGISTRY = []; }; \
TAG_REGISTRY pushBack #FACTION_ID; \
LOADOUT_REGISTRY() = []; \
CLASS_REGISTRY() = []; \
CRATE_REGISTRY() = []

#define LOADOUT_VARIABLE(SUFFIX_LOADOUT) baf_loadout_##FACTION_ID##_##SUFFIX_LOADOUT
#define LOADOUT_REGISTRY() baf_registry_loadout_##FACTION_ID
#define LOADOUT_NAME(SUFFIX_LOADOUT) (LOADOUT_VARIABLE(SUFFIX_LOADOUT) select 0)
#define LOADOUT_TRAITS(SUFFIX_LOADOUT) (LOADOUT_VARIABLE(SUFFIX_LOADOUT) select 2)

#define CLASS_VARIABLE(SUFFIX_CLASS) baf_class_##FACTION_ID##_##SUFFIX_CLASS
#define CLASS_REGISTRY() baf_registry_class_##FACTION_ID
#define CLASS_LOADOUT_VALUE(SUFFIX_LOADOUT) [#LOADOUT_VARIABLE(SUFFIX_LOADOUT),LOADOUT_NAME(SUFFIX_LOADOUT)]

#define CRATE_VARIABLE(SUFFIX_CRATE) baf_crate_##FACTION_ID##_##SUFFIX_CRATE
#define CRATE_REGISTRY() baf_registry_crate_##FACTION_ID

// Loadout Variable: [0) Display Name,1) Loadout Array,2) Traits Array,3) Radio Key]
#define CREATE_LOADOUT(SUFFIX_LOADOUT,DISPLAY_NAME,LOADOUT_ARRAY) \
LOADOUT_REGISTRY() pushBack [#SUFFIX_LOADOUT,DISPLAY_NAME]; \
LOADOUT_VARIABLE(SUFFIX_LOADOUT) = [DISPLAY_NAME,LOADOUT_ARRAY select 0,[0,0]] // TODO: Add additional values to trait array and radio key
#define COPY_LOADOUT(SUFFIX_LOADOUT_NEW,DISPLAY_NAME,SUFFIX_LOADOUT_OLD) \
LOADOUT_REGISTRY() pushBack [#SUFFIX_LOADOUT_NEW,DISPLAY_NAME]; \
LOADOUT_VARIABLE(SUFFIX_LOADOUT_NEW) = +LOADOUT_VARIABLE(SUFFIX_LOADOUT_OLD)
#define RESET_TRAITS(SUFFIX_LOADOUT) \
LOADOUT_TRAITS(SUFFIX_LOADOUT) set [0,0]; \
LOADOUT_TRAITS(SUFFIX_LOADOUT) set [1,0]
// TODO: Reset additional traits
#define LO_SET_MEDIC(SUFFIX_LOADOUT) LOADOUT_TRAITS(SUFFIX_LOADOUT) set [0,1]
#define LO_SET_DOCTOR(SUFFIX_LOADOUT) LOADOUT_TRAITS(SUFFIX_LOADOUT) set [0,2]
#define LO_SET_ENGINEER(SUFFIX_LOADOUT) LOADOUT_TRAITS(SUFFIX_LOADOUT) set [1,1]
// #define ADD_RADIO_KEY(SUFFIX,STRING_KEY) LOADOUT_VARIABLE(SUFFIX) set [3,STRING_KEY]; // TODO: Enable Radio Key Functionality 
// TODO: Add additional customization
// TODO: Create Default Loadout Syntax

#define CREATE_CLASS(SUFFIX_CLASS,DISPLAY_NAME,SUFFIX_LOADOUT) \
CLASS_REGISTRY() pushBack [#SUFFIX_CLASS,DISPLAY_NAME]; \
CLASS_VARIABLE(SUFFIX_CLASS) = [[CLASS_LOADOUT_VALUE(SUFFIX_LOADOUT)],[]]
#define CL_ADD_LOADOUT(SUFFIX_CLASS,SUFFIX_LOADOUT) (CLASS_VARIABLE(SUFFIX_CLASS) select 0) pushBack CLASS_LOADOUT_VALUE(SUFFIX_LOADOUT)
#define CL_ADD_ARSENAL_ITEMS(SUFFIX_CLASS,ITEM_ARRAY) BAF_fnc_addItemsToArsenal;

#define CREATE_CRATE(SUFFIX_CRATE,DISPLAY_NAME) \
CRATE_REGISTRY() pushBack [#SUFFIX_CRATE,DISPLAY_NAME]; \
CRATE_VARIABLE(SUFFIX_CRATE) = []
#define CR_ADD_ITEM(SUFFIX_CRATE,ITEM_NAME,COUNT) \
[] call BAF_fnc_addItemToCrate
#define CR_ADD_PRIMARY(SUFFIX_CRATE,SUFFIX_LOADOUT,COUNT) \
[#SUFFIX_CRATE,#SUFFIX_LOADOUT,COUNT,#FACTION_ID] call BAF_fnc_addPrimaryToCrate
#define CR_ADD_SECONDARY(SUFFIX_CRATE,SUFFIX_LOADOUT,COUNT) \
[] call BAF_fnc_addSecondaryToCrate
#define CR_ADD_LAUNCHER(SUFFIX_CRATE,SUFFIX_LOADOUT,COUNT) \
[] call BAF_fnc_addLauncherToCrate
#define CR_ADD_PRIMARY_MAGS(SUFFIX_CRATE,SUFFIX_LOADOUT,COUNT) \
[#SUFFIX_CRATE,#SUFFIX_LOADOUT,COUNT,#FACTION_ID] call BAF_fnc_addPrimaryMagsToCrate
#define CR_ADD_SECONDARY_MAGS(SUFFIX_CRATE,SUFFIX_LOADOUT,COUNT) \
[] call BAF_fnc_addSecondaryMagsToCrate
#define CR_ADD_LAUNCHER_MAGS(SUFFIX_CRATE,SUFFIX_LOADOUT,COUNT) \
[] call BAF_fnc_addLauncherMagsToCrate
// #define CR_ADD_MEDICAL(SUFFIX_CRATE,MULTIPLIER) \
// TODO: Define createCrateFromFaction
// TODO: Defome createCrateFromClass
