
#define CONCAT(VALUE1, VALUE2) VALUE1##VALUE2
#define CONCAT3(VALUE1, VALUE2, VALUE3) VALUE1##VALUE2##VALUE3
#define CONCAT3(VALUE1, VALUE2, VALUE3, VALUE4) VALUE1##VALUE2##VALUE3##VALUE4

#define STRING(VALUE) #VALUE

#define GETVARM(VARIABLE, DEFAULT) missionNamespace getVaraible [VARIABLE, DEFAULT]

