
#define STR(ARG) #ARG
#define WEST westy

#define CONCAT(VALUE1,VALUE2) VALUE1##VALUE2
#define CONCAT3(VALUE1,VALUE2,VALUE3) VALUE1##VALUE2##VALUE3
#define CONCAT4(VALUE1,VALUE2,VALUE3,VALUE4) VALUE1##VALUE2##VALUE3##VALUE4

#define SVAR(VAR) #VAR
#define BVAR(PREFIX,VAR) CONCAT4(bax_,PREFIX,_,VAR)
#define BSVAR(PREFIX,VAR) SVAR(BVAR(PREFIX,VAR))
#define BFUNC(PREFIX,FUNC) CONCAT4(bax_,PREFIX,_fnc_,FUNC)
#define BCFUNC(PREFIX,FUNC) SVAR(CONCAT4(call bax_,PREFIX,_fnc_,FUNC))
#define BSFUNC(PREFIX,FUNC) SVAR(CONCAT4(bax_,PREFIX,_fnc_,FUNC))
#define BMCFG(VALUE) (missionConfigFile >> "BAXCFG" >> #VALUE)
